package com.reefbot.enums;

public enum PlayerScreen {
    MAIN,
    MY_ISLAND,
    ZONE_FOREST,
    ZONE_SHORE,
    ZONE_SETTLEMENT,
    ZONE_HILLS,
    ZONE_PLAINS,
    ZONE_PORT,
    FISHING_MENU,
    FISHING_ACTIVE,
    FISHING_RESULT,
    FISHING_BONUSES,
    ZONE_SHORE_BEACH,
    ZONE_SHORE_TIDE,
    ZONE_SHORE_BUILDINGS,
    ZONE_SHORE_PIER,
    FISHING_INVENTORY,
    NPC_ENCOUNTER
}
